/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The P model module.
 * @module model/P
 * @version 1.0.0
 */
class P {
    /**
     * Constructs a new <code>P</code>.
     * @alias module:model/P
     * @param ptitle {String} 
     */
    constructor(ptitle) { 
        
        P.initialize(this, ptitle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ptitle) { 
        obj['ptitle'] = ptitle;
    }

    /**
     * Constructs a <code>P</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/P} obj Optional instance to populate.
     * @return {module:model/P} The populated <code>P</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new P();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('ptitle')) {
                obj['ptitle'] = ApiClient.convertToType(data['ptitle'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
P.prototype['_id'] = undefined;

/**
 * @member {String} ptitle
 */
P.prototype['ptitle'] = undefined;






export default P;

